#!/bin/bash
# Test Script: Verify Spoofed MAC Detection works across the entire pipeline
# Assumes Backend, Packet-Capture, and Prevention Engine are running

echo "Testing Fake Deauthentication Attack"

# Mock Attack Packet Event Data sent to the backend as generated by data_sender.py
curl -X POST http://localhost:8080/api/packets/deauth \
-H "Content-Type: application/json" \
-d '{
  "sourceMac": "AA:BB:CC:DD:EE:FF", 
  "destMac": "11:22:33:44:55:66", 
  "bssid": "11:22:33:44:55:66",
  "sequence": 1234,
  "rssi": -30,
  "reason": 7,
  "frameType": "DEAUTH",
  "isSpoofed": true,
  "realAttackerMac": "66:55:44:33:22:11",
  "rssiDeviation": 15.5,
  "apBaselineRssi": -45.5,
  "detectionMethod": "RSSI",
  "scoreBoost": 20,
  "attackConfidence": 95,
  "attackRate": 50.0,
  "uniqueVictims": 1,
  "totalDeauths": 100
}'

echo ""
echo "Attack Packet injected!"
echo "- Check Backend Logs for 'Critical Deauth Attack' mentioning true attacker: 66:55:44:33:22:11"
echo "- Check Admin UI for real attacker MAC vs target MAC"
echo "- Check Prevention Engine Logs for 'MAXIMUM DEFENSE ACTIVATED' and 'Honeypot deployed'"
