package com.wifi.security.util;

import com.wifi.security.entity.CapturedPacket;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Builder utility for creating CapturedPacket entities in tests.
 * Follows the Builder pattern for fluent, readable test setup.
 * 
 * Usage:
 * 
 * <pre>
 * CapturedPacket packet = new CapturedPacketBuilder()
 *         .withSourceMac("00:11:22:33:44:55")
 *         .withBssid("AA:BB:CC:DD:EE:FF")
 *         .withFrameType("DEAUTH")
 *         .withTimestamp(LocalDateTime.now())
 *         .build();
 * </pre>
 */
public class CapturedPacketBuilder {

    private String id;
    private String sourceMac = "00:00:00:00:00:00";
    private String destMac = "FF:FF:FF:FF:FF:FF"; // Default broadcast
    private String bssid = "00:00:00:00:00:00";
    private Integer sequenceNumber = 0;
    private Integer rssi = -50;
    private LocalDateTime timestamp = LocalDateTime.now();
    private String frameType = "DEAUTH";
    private LocalDateTime receivedAt = LocalDateTime.now();

    /**
     * Sets the packet ID. If not set, a UUID will be generated.
     */
    public CapturedPacketBuilder withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Sets the source MAC address.
     */
    public CapturedPacketBuilder withSourceMac(String sourceMac) {
        this.sourceMac = sourceMac;
        return this;
    }

    /**
     * Sets the destination MAC address.
     */
    public CapturedPacketBuilder withDestMac(String destMac) {
        this.destMac = destMac;
        return this;
    }

    /**
     * Sets the BSSID (Access Point MAC).
     */
    public CapturedPacketBuilder withBssid(String bssid) {
        this.bssid = bssid;
        return this;
    }

    /**
     * Sets the 802.11 sequence number (0-4095).
     */
    public CapturedPacketBuilder withSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    /**
     * Sets the RSSI signal strength.
     */
    public CapturedPacketBuilder withRssi(Integer rssi) {
        this.rssi = rssi;
        return this;
    }

    /**
     * Sets the packet timestamp.
     */
    public CapturedPacketBuilder withTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * Sets the 802.11 frame type (DEAUTH, DISASSOC, AUTH, ASSOC, PROBE, etc.).
     */
    public CapturedPacketBuilder withFrameType(String frameType) {
        this.frameType = frameType;
        return this;
    }

    /**
     * Sets the time when the packet was received by the system.
     */
    public CapturedPacketBuilder withReceivedAt(LocalDateTime receivedAt) {
        this.receivedAt = receivedAt;
        return this;
    }

    /**
     * Builds and returns a new CapturedPacket entity.
     * Note: The ID is NOT set here because the entity uses @GeneratedValue(UUID).
     * JPA will generate the ID on persist.
     */
    public CapturedPacket build() {
        CapturedPacket packet = new CapturedPacket();
        // ID is auto-generated by JPA, so we don't set it unless explicitly provided
        // packet.setId(id != null ? id : UUID.randomUUID().toString());
        packet.setSourceMac(sourceMac);
        packet.setDestMac(destMac);
        packet.setBssid(bssid);
        packet.setSequenceNumber(sequenceNumber);
        packet.setRssi(rssi);
        packet.setTimestamp(timestamp);
        packet.setFrameType(frameType);
        // receivedAt is set by @PrePersist in entity, but we can set it for tests
        // packet.setReceivedAt(receivedAt);
        return packet;
    }

    /**
     * Builds a packet with a manually set ID (useful for unit tests without JPA).
     */
    public CapturedPacket buildWithId() {
        CapturedPacket packet = build();
        packet.setId(id != null ? id : UUID.randomUUID().toString());
        return packet;
    }

    /**
     * Creates a copy of the current builder for creating variations.
     */
    public CapturedPacketBuilder copy() {
        return new CapturedPacketBuilder()
                .withId(this.id)
                .withSourceMac(this.sourceMac)
                .withDestMac(this.destMac)
                .withBssid(this.bssid)
                .withSequenceNumber(this.sequenceNumber)
                .withRssi(this.rssi)
                .withTimestamp(this.timestamp)
                .withFrameType(this.frameType)
                .withReceivedAt(this.receivedAt);
    }

    /**
     * Factory method for creating a deauth packet builder with common defaults.
     */
    public static CapturedPacketBuilder deauthPacket() {
        return new CapturedPacketBuilder()
                .withFrameType("DEAUTH")
                .withDestMac("FF:FF:FF:FF:FF:FF");
    }

    /**
     * Factory method for creating a disassoc packet builder.
     */
    public static CapturedPacketBuilder disassocPacket() {
        return new CapturedPacketBuilder()
                .withFrameType("DISASSOC");
    }

    /**
     * Factory method for creating an auth packet builder.
     */
    public static CapturedPacketBuilder authPacket() {
        return new CapturedPacketBuilder()
                .withFrameType("AUTH");
    }
}
